### ISSUE TITLE
JpmsProvidesValidator crashed with InvalidModuleDescriptorException

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#127]
JpmsProvidesValidator crashed failed with:
```
An exception occured:
java.lang.RuntimeException: java.lang.module.InvalidModuleDescriptorException: CONSTANT_Class at entry 91 has illegal character: '.'
at org.fedoraproject.javapackages.validator.util.RpmJarConsumer.accept(RpmJarConsumer.java:23)
at org.fedoraproject.javapackages.validator.util.JarValidator.validate(JarValidator.java:23)
at org.fedoraproject.javapackages.validator.validators.JpmsProvidesValidator.validate(JpmsProvidesValidator.java:92)
at org.fedoraproject.javapackages.validator.util.ElementwiseValidator.validate(ElementwiseValidator.java:27)
at org.fedoraproject.javapackages.validator.DefaultValidator.validate(DefaultValidator.java:22)
at org.fedoraproject.javapackages.validator.Main.lambda$execute$18(Main.java:559)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3252)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2191)
at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2157)
at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.module.InvalidModuleDescriptorException: CONSTANT_Class at entry 91 has illegal character: '.'
at java.base/jdk.internal.module.ModuleInfo.invalidModuleDescriptor(ModuleInfo.java:1216)
at java.base/jdk.internal.module.ModuleInfo$ConstantPool.checkUnqualifiedName(ModuleInfo.java:875)
at java.base/jdk.internal.module.ModuleInfo$ConstantPool.getClassName(ModuleInfo.java:824)
at java.base/jdk.internal.module.ModuleInfo.readModuleMainClassAttribute(ModuleInfo.java:567)
at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:259)
at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:145)
at java.base/java.lang.module.ModuleDescriptor.read(ModuleDescriptor.java:2611)
at org.fedoraproject.javapackages.validator.validators.JpmsProvidesValidator.acceptJarEntry(JpmsProvidesValidator.java:41)
at org.fedoraproject.javapackages.validator.validators.jp.JpmsProvidesValidatorJP.acceptJarEntry(JpmsProvidesValidatorJP.java:21)
at org.fedoraproject.javapackages.validator.util.RpmJarConsumer.accept(RpmJarConsumer.java:19)
... 18 more
```
In case of invalid module descriptor I expect test failure with appropriate explanation and not crash.

**Comment by mizdebsk** [comment]
The issue seems to be in RpmJarConsumer:
```
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
```
In case of Exception the test should fail and JPV should not crash.
