### ISSUE TITLE
NullPointerException in Rule.is_applicable() when config specifies <all> match

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#2]
Reproducer:

```
<config>
  <execution>
    <tag>foo</tag>
  </execution>
  <rule>
    <name>bar</name>
    <tag>foo</tag>
    <match>
      <all>
	<name>x</name>
        <release>y</release>
      </all>
    </match>
  </rule>
</config>
```

Traceback:

```
Exception in thread "main" java.lang.NullPointerException
	at org.fedoraproject.javapackages.validator.Rule.is_applicable(Rule.java:419)
	at org.fedoraproject.javapackages.validator.Rule$Structured$Tag.do_apply(Rule.java:116)
	at org.fedoraproject.javapackages.validator.Rule$Structured.apply(Rule.java:52)
	at org.fedoraproject.javapackages.validator.Package_test.main(Package_test.java:224)
```

**Comment by mizdebsk** [comment]
I propose to close this as the old code is no longer maintained.

**Comment by mkoncek** [comment]
Validator is being rewritten, so this issue is no longer valid.
